//! Ordered parallel mapping for the generation stages.
//!
//! Emitting a large SDK is thousands of independent renders: one file per schema, each a pure
//! function of the frozen graph and its own schema. That work parallelizes exactly, and on a
//! 1,576-model project it is the single largest cost in a warm run.
//!
//! [`map_ordered`] is the only way this crate spreads that work. It is deliberately not a general
//! scheduler:
//!
//! * **Order is by index, never by completion.** Each worker fills a contiguous span and the spans
//!   are concatenated in input order, so the result sequence — and therefore the generated bytes —
//!   is identical at any thread count, including one. Thread count is a machine fact; output is not
//!   allowed to be.
//! * **The reported failure is the lowest-index one**, for the same reason: which worker happened to
//!   fail first is a scheduling accident, and a diagnostic that changes run to run is not a
//!   diagnostic.
//! * **A worker that panics becomes a typed error**, never a propagated unwind (RUST-04).

use crate::CoreError;

/// Below this many items the work is smaller than the cost of handing it out.
const MIN_PARALLEL_ITEMS: usize = 64;

/// Workers to use for `len` items: never more than there is work, or the machine has cores.
fn worker_count(len: usize) -> usize {
    if len < MIN_PARALLEL_ITEMS {
        return 1;
    }
    std::thread::available_parallelism()
        .map_or(1, std::num::NonZeroUsize::get)
        .min(len)
}

/// Map `items` through `render` across the machine's cores, preserving input order.
///
/// # Errors
///
/// Returns `render`'s failure for the LOWEST-index item that failed, or [`CoreError::SdkGen`] if a
/// worker panicked.
pub(crate) fn map_ordered<T, R, F>(items: &[T], render: F) -> Result<Vec<R>, CoreError>
where
    T: Sync,
    R: Send,
    F: Fn(&T) -> Result<R, CoreError> + Sync,
{
    let workers = worker_count(items.len());
    if workers <= 1 {
        return items.iter().map(render).collect();
    }
    let span = items.len().div_ceil(workers);
    let render = &render;
    let spans: Vec<Result<Vec<R>, (usize, CoreError)>> = std::thread::scope(|scope| {
        let handles: Vec<_> = items
            .chunks(span)
            .enumerate()
            .map(|(index, chunk)| {
                scope.spawn(move || {
                    let mut rendered = Vec::with_capacity(chunk.len());
                    for (offset, item) in chunk.iter().enumerate() {
                        match render(item) {
                            Ok(value) => rendered.push(value),
                            Err(err) => return Err((index * span + offset, err)),
                        }
                    }
                    Ok(rendered)
                })
            })
            .collect();
        handles
            .into_iter()
            .map(|handle| {
                handle.join().unwrap_or_else(|_| {
                    Err((
                        usize::MAX,
                        CoreError::SdkGen {
                            message: "a generation worker thread stopped unexpectedly".to_string(),
                        },
                    ))
                })
            })
            .collect()
    });

    let mut rendered = Vec::with_capacity(items.len());
    let mut failure: Option<(usize, CoreError)> = None;
    for span in spans {
        match span {
            Ok(values) => rendered.extend(values),
            Err((position, err)) => {
                if failure.as_ref().is_none_or(|(seen, _)| position < *seen) {
                    failure = Some((position, err));
                }
            }
        }
    }
    match failure {
        Some((_, err)) => Err(err),
        None => Ok(rendered),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::{map_ordered, MIN_PARALLEL_ITEMS};
    use crate::CoreError;

    #[test]
    fn results_follow_input_order_not_completion_order() {
        let items: Vec<usize> = (0..MIN_PARALLEL_ITEMS * 8).collect();
        let rendered = map_ordered(&items, |item| {
            // Make the early items the slow ones, so completion order is the reverse of input order.
            std::thread::sleep(std::time::Duration::from_micros(
                u64::try_from(items.len() - item).unwrap_or(0),
            ));
            Ok(item * 2)
        })
        .unwrap();
        assert_eq!(
            rendered,
            items.iter().map(|item| item * 2).collect::<Vec<_>>()
        );
    }

    #[test]
    fn a_short_input_and_a_long_one_render_the_same_sequence() {
        let short: Vec<usize> = (0..MIN_PARALLEL_ITEMS - 1).collect();
        let long: Vec<usize> = (0..MIN_PARALLEL_ITEMS * 4).collect();
        let render = |item: &usize| Ok(item.to_string());
        assert_eq!(
            map_ordered(&short, render).unwrap(),
            short.iter().map(usize::to_string).collect::<Vec<_>>()
        );
        assert_eq!(
            map_ordered(&long, render).unwrap(),
            long.iter().map(usize::to_string).collect::<Vec<_>>()
        );
    }

    #[test]
    fn the_reported_failure_is_the_lowest_index_one() {
        let items: Vec<usize> = (0..MIN_PARALLEL_ITEMS * 8).collect();
        let err = map_ordered(&items, |item| {
            if *item % 7 == 3 {
                return Err(CoreError::SdkGen {
                    message: format!("item {item}"),
                });
            }
            Ok(*item)
        })
        .unwrap_err();
        assert!(err.to_string().contains("item 3"), "{err}");
    }
}
