//! The lifecycle write-decision core: the PURE `plan_writes` truth table, the impure `apply_writes`
//! shell, naming-override application, and the `regenerate`/`plan_only` orchestrators the binary
//! calls (WS-04, WATCH-01, WS-03 / D-04, D-05).
//!
//! ## The heart of the phase — a pure decision, a thin shell
//!
//! [`plan_writes`] is a PURE function over (freshly generated bytes, the previous-run manifest, an
//! injected on-disk reader). It classifies each output as [`WriteAction::Write`],
//! [`WriteAction::Unchanged`] (no-op), or [`WriteAction::UserEdited`] (a human hand-edited a
//! generated file, or a pre-existing untracked file sits at an output path). Because it does NO
//! I/O — on-disk bytes come solely from the injected closure — the full truth table is exhaustively
//! unit-testable without a filesystem (RESEARCH Pattern 2 / Pitfall 3). The `--force` policy lives in
//! [`apply_writes`], NOT here, so the classification stays pure and the override decision stays in
//! one place.
//!
//! [`apply_writes`] is the impure half: it writes `Write` (and, under `force`, `UserEdited`) files,
//! skips `Unchanged`/`UserEdited`, records new hashes, and prunes manifest entries for paths no
//! longer produced (D-04). It resolves every output path against the project root and REJECTS paths
//! that escape it (path-traversal hardening, T-04-02-01 — output paths come from user config, so the
//! `sdk::write_to_dir` frame-name discipline is extended to user-supplied paths here).
//!
//! [`regenerate`] ties it together: build the graph, apply naming overrides, lower to OpenAPI +
//! generate the SDK bundle, assemble the per-file outputs, load the manifest, `plan_writes`,
//! `apply_writes`, save the manifest, and return a [`GenerateOutcome`] with written/unchanged/skipped
//! counts. [`plan_only`] runs the same pipeline up to the WritePlan WITHOUT touching disk — the
//! dry-run seam `gnr8 check` uses. No production `unwrap`/`expect`/`panic` (RUST-04).

// Acronym-dense prose (WS-04, WATCH-01, OpenAPI, blake3, D-04, ...); allow `doc_markdown` module-wide
// (skill ch.2.4, mirrors config/mod.rs and manifest/mod.rs).
#![allow(clippy::doc_markdown)]

use std::path::{Component, Path};

use crate::config::{Config, NamingOverrides};
use crate::graph::ApiGraph;
use crate::manifest::{self, blake3_hex, Manifest};

/// The provenance tag recorded for the OpenAPI artifact.
const SOURCE_OPENAPI: &str = "openapi";
/// The provenance tag recorded for every generated SDK file.
const SOURCE_SDK: &str = "sdk";

/// Per-file classification produced by [`plan_writes`] (the WS-04 / WATCH-01 truth table).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteAction {
    /// New file (absent on disk) or a gnr8-owned file whose content changed ⇒ write it.
    Write,
    /// On-disk bytes are byte-identical to the freshly generated bytes ⇒ skip the write (no-op,
    /// WATCH-01 / D-05: no mtime churn).
    Unchanged,
    /// On-disk hash != the recorded hash (a human edited a generated file), or the path is present
    /// on disk but ABSENT from the manifest (a pre-existing hand-written output). Warn + skip unless
    /// `--force` (WS-04 / D-04, Pitfall 5).
    UserEdited,
}

/// One planned output: its project-relative path, the decided [`WriteAction`], the freshly generated
/// bytes, the blake3 hash of those bytes, and the generator provenance.
#[derive(Debug, Clone)]
pub struct PlannedFile {
    /// The project-relative output path (e.g. `"openapi.yaml"`, `"sdk/client.go"`).
    pub path: String,
    /// What [`plan_writes`] decided to do with this file.
    pub action: WriteAction,
    /// The freshly generated bytes for this path (deterministic — Phase 2-3).
    pub new_bytes: Vec<u8>,
    /// The blake3 hash of `new_bytes` (recorded in the manifest when written).
    pub new_hash: String,
    /// Generator provenance (`"openapi"` | `"sdk"`).
    pub source: String,
}

/// The per-file write plan: the classification of every output for this generation.
#[derive(Debug, Clone, Default)]
pub struct WritePlan {
    /// One [`PlannedFile`] per generated output, in generation order.
    pub files: Vec<PlannedFile>,
}

impl WritePlan {
    /// Whether any planned file is stale (`Write`) or drifted (`UserEdited`) — the dry-run drift
    /// signal `gnr8 check` exits non-zero on (every file `Unchanged` ⇒ clean).
    #[must_use]
    pub fn has_drift(&self) -> bool {
        self.files
            .iter()
            .any(|f| matches!(f.action, WriteAction::Write | WriteAction::UserEdited))
    }
}

/// Counts of what a generation did, returned by [`apply_writes`]/[`regenerate`].
///
/// Derives `serde::Serialize` for the `--json` latency report (04-03 serializes it).
#[derive(Debug, Default, Clone, serde::Serialize)]
pub struct GenerateOutcome {
    /// Paths that were written (new or changed; under `force`, also overwritten user edits).
    pub written: Vec<String>,
    /// Paths that were byte-identical and therefore NOT rewritten (no-op).
    pub unchanged: Vec<String>,
    /// Paths that were protected (user-edited / pre-existing untracked) and skipped without `force`.
    pub skipped: Vec<String>,
}

/// Classify each generated output — the PURE heart of WS-04 / WATCH-01.
///
/// `new_outputs` are `(project-relative path, freshly generated bytes)`. `manifest` is the
/// previous-run record. `on_disk` returns the path's CURRENT bytes (or `None` if absent). NO I/O:
/// on-disk bytes come solely from the injected closure, which is what makes the full truth table
/// unit-testable without a filesystem. The five arms (RESEARCH Pattern 2):
///
/// 1. absent on disk ⇒ [`WriteAction::Write`]
/// 2. present, recorded, on-disk hash == recorded, new == disk ⇒ [`WriteAction::Unchanged`]
/// 3. present, recorded, on-disk hash == recorded, new != disk ⇒ [`WriteAction::Write`]
/// 4. present, recorded, on-disk hash != recorded ⇒ [`WriteAction::UserEdited`]
/// 5. present, NOT in manifest ⇒ [`WriteAction::UserEdited`] (protect a pre-existing output)
///
/// `--force` is NOT applied here (it lives in [`apply_writes`]) so the classification stays pure.
#[must_use]
pub fn plan_writes(
    new_outputs: &[(String, Vec<u8>)],
    manifest: &Manifest,
    on_disk: &dyn Fn(&str) -> Option<Vec<u8>>,
) -> WritePlan {
    plan_writes_with_sources(
        &new_outputs
            .iter()
            .map(|(p, b)| (p.clone(), b.clone(), SOURCE_SDK.to_string()))
            .collect::<Vec<_>>(),
        manifest,
        on_disk,
    )
}

/// [`plan_writes`] with an explicit per-file provenance tag (used by [`regenerate`]/[`plan_only`] so
/// the manifest records `"openapi"` vs `"sdk"`). Same pure classification; no I/O.
#[must_use]
fn plan_writes_with_sources(
    new_outputs: &[(String, Vec<u8>, String)],
    manifest: &Manifest,
    on_disk: &dyn Fn(&str) -> Option<Vec<u8>>,
) -> WritePlan {
    let mut files = Vec::with_capacity(new_outputs.len());
    for (path, new_bytes, source) in new_outputs {
        let new_hash = blake3_hex(new_bytes);
        // The five arms are the documented WS-04/WATCH-01 truth table; arms 1 and 3 deliberately
        // share the `Write` body but are kept as distinct, separately-commented cases for clarity
        // (collapsing them would hide the difference between "absent" and "owned-but-changed").
        #[allow(clippy::match_same_arms)]
        let action = match (on_disk(path), manifest.recorded_hash(path)) {
            // 1. absent on disk → always write (fresh generation or user deleted it).
            (None, _) => WriteAction::Write,
            // 4. present, recorded, but its CURRENT hash != what we last wrote → user hand-edited it.
            (Some(disk), Some(recorded)) if blake3_hex(&disk) != recorded => {
                WriteAction::UserEdited
            }
            // 2. present, gnr8-owned, byte-identical to the new output → no-op skip.
            (Some(disk), Some(_)) if disk == *new_bytes => WriteAction::Unchanged,
            // 3. present, gnr8-owned, content changed → write the update.
            (Some(_), Some(_)) => WriteAction::Write,
            // 5. present but NOT in the manifest → never written by gnr8 → treat as a user file.
            (Some(_), None) => WriteAction::UserEdited,
        };
        files.push(PlannedFile {
            path: path.clone(),
            action,
            new_bytes: new_bytes.clone(),
            new_hash,
            source: source.clone(),
        });
    }
    WritePlan { files }
}

/// Materialize a [`WritePlan`] to disk (the impure half, RESEARCH Pattern 3).
///
/// For each file: `Write` (and `UserEdited` when `force`) → validate the path against `project_root`,
/// write the bytes, record the new hash in `manifest`, push to `written`. `Unchanged` → push to
/// `unchanged` (NO write — no mtime churn). `UserEdited` without `force` → push to `skipped` (the
/// CLI warns). After the loop, prune manifest entries for paths no longer produced (D-04).
///
/// Output paths come from user config, so each is resolved against `project_root` and REJECTED if it
/// escapes it (contains a `..`/root/prefix component) — path-traversal hardening (T-04-02-01,
/// extending the `sdk::write_to_dir` frame-name discipline to user-supplied paths).
///
/// # Errors
///
/// Returns [`crate::CoreError::Io`] for a path that escapes the project root or a file that cannot be
/// written (with an actionable message). Never panics.
pub fn apply_writes(
    project_root: &Path,
    plan: &WritePlan,
    manifest: &mut Manifest,
    force: bool,
) -> Result<GenerateOutcome, crate::CoreError> {
    let mut out = GenerateOutcome::default();
    for file in &plan.files {
        let should_write = match file.action {
            WriteAction::Write => true,
            WriteAction::UserEdited => force,
            WriteAction::Unchanged => false,
        };
        if should_write {
            let safe = safe_output_path(project_root, &file.path)?;
            if let Some(parent) = safe.parent() {
                std::fs::create_dir_all(parent).map_err(|err| crate::CoreError::Io {
                    message: format!("failed to create {}: {err}", parent.display()),
                })?;
            }
            std::fs::write(&safe, &file.new_bytes).map_err(|err| crate::CoreError::Io {
                message: format!("failed to write {}: {err}", safe.display()),
            })?;
            manifest.record(&file.path, &file.new_hash, &file.source);
            out.written.push(file.path.clone());
        } else if file.action == WriteAction::Unchanged {
            out.unchanged.push(file.path.clone());
        } else {
            // UserEdited without force → protected, skipped (CLI warns naming the file).
            out.skipped.push(file.path.clone());
        }
    }

    // D-04: drop manifest entries for paths this generation no longer produces.
    let current_paths: Vec<String> = plan.files.iter().map(|f| f.path.clone()).collect();
    manifest.prune_to(&current_paths);
    Ok(out)
}

/// Resolve a user-config output path against `project_root`, REJECTING any path that escapes the root
/// (absolute, root-anchored, or containing a `..` component) — path-traversal defense (T-04-02-01).
///
/// # Errors
///
/// Returns [`crate::CoreError::Io`] for an empty path or one that would escape the project root.
fn safe_output_path(
    project_root: &Path,
    rel: &str,
) -> Result<std::path::PathBuf, crate::CoreError> {
    if rel.is_empty() {
        return Err(crate::CoreError::Io {
            message: "refusing to write an empty output path".to_string(),
        });
    }
    let candidate = Path::new(rel);
    for component in candidate.components() {
        match component {
            // A normal path segment is fine; current-dir (`.`) is harmless.
            Component::Normal(_) | Component::CurDir => {}
            // `..`, a root `/`, or a Windows prefix could escape the project root → reject.
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(crate::CoreError::Io {
                    message: format!(
                        "refusing to write output path {rel:?}: it escapes the project root \
                         (no absolute paths or `..` segments allowed)"
                    ),
                });
            }
        }
    }
    Ok(project_root.join(candidate))
}

/// Apply naming overrides to the graph IN PLACE before lowering (WS-03).
///
/// - Each `operation.id` present in `naming.operations` is remapped to its new value (the operationId
///   the OpenAPI/SDK output uses).
/// - Each schema matched by `naming.types` (by `id` OR bare `name`) is renamed: BOTH its `id` and
///   `name` become the new value, AND **every** `SchemaRef.ref_id` / field `SchemaType.ref_id` that
///   pointed at the old id is rewritten to the new value. This is MANDATORY (PLAN-CHECK W2): a
///   referenced type renamed without updating its $refs would dangle and make `to_openapi` fail with
///   `CoreError::Lowering`. By keeping `id == name == new value` and rewriting every ref, the
///   component key, the resolved `$ref` name, and the references all stay consistent.
///
/// A key with no matching operation/schema is a silent no-op (NOT an error).
pub fn apply_naming(graph: &mut ApiGraph, naming: &NamingOverrides) {
    // Operation-id remaps.
    for op in &mut graph.operations {
        if let Some(new_id) = naming.operations.get(&op.id) {
            op.id = new_id.clone();
        }
    }

    // Type remaps: rename the schema (id + name) AND rewrite every ref pointing at the old id.
    for (key, new_name) in &naming.types {
        // Find the schema by id or bare name; capture its current id so we can rewrite refs.
        let Some(old_id) = graph
            .schemas
            .iter()
            .find(|s| &s.id == key || &s.name == key)
            .map(|s| s.id.clone())
        else {
            continue; // unmatched key → silent no-op
        };

        // Rename the schema itself (both id and name → the new value).
        for schema in &mut graph.schemas {
            if schema.id == old_id {
                schema.id.clone_from(new_name);
                schema.name.clone_from(new_name);
            }
        }

        // Rewrite every reference to the old id so no $ref dangles (PLAN-CHECK W2).
        for schema in &mut graph.schemas {
            for field in &mut schema.fields {
                rewrite_schema_type_ref(&mut field.schema, &old_id, new_name);
            }
        }
        for op in &mut graph.operations {
            if let Some(body) = op.request_body.as_mut() {
                if body.ref_id == old_id {
                    body.ref_id.clone_from(new_name);
                }
            }
            for resp in &mut op.responses {
                if let Some(body) = resp.body.as_mut() {
                    if body.ref_id == old_id {
                        body.ref_id.clone_from(new_name);
                    }
                }
            }
            for param in &mut op.params {
                rewrite_schema_type_ref(&mut param.schema, &old_id, new_name);
            }
        }
    }
}

/// Rewrite a `ref`-kind [`crate::graph::SchemaType`]'s `ref_id` (recursing into array `items`) from
/// `old_id` to `new_id`, so a renamed schema's references stay valid (PLAN-CHECK W2).
fn rewrite_schema_type_ref(schema: &mut crate::graph::SchemaType, old_id: &str, new_id: &str) {
    if let Some(ref_id) = schema.ref_id.as_mut() {
        if ref_id == old_id {
            *ref_id = new_id.to_string();
        }
    }
    if let Some(items) = schema.items.as_mut() {
        rewrite_schema_type_ref(items, old_id, new_id);
    }
}

/// Build the full set of generated outputs `(project-relative path, bytes, provenance)` for `config`.
///
/// Runs the deterministic Phase 2-3 pipeline: build the graph over the first configured input dir,
/// apply naming overrides, lower to OpenAPI, generate the SDK bundle, and split the bundle into
/// per-file outputs under `output.sdk_dir` (with the frame-name path-safety check). The Go-toolchain /
/// lowering / sdkgen errors propagate as their existing typed `CoreError` variants.
///
/// PoC scope: if `config.inputs` has more than one entry, only the FIRST is analyzed (multi-input
/// fan-in is out of scope this phase — D-02).
fn build_outputs(config: &Config) -> Result<Vec<(String, Vec<u8>, String)>, crate::CoreError> {
    let input = config
        .inputs
        .first()
        .ok_or_else(|| crate::CoreError::Config {
            message: "config.inputs is empty — at least one Go source dir is required".to_string(),
        })?;

    let mut graph = crate::analyze::build_graph(input)?;
    apply_naming(&mut graph, &config.naming);

    let openapi = crate::lower::to_openapi(&graph)?;
    let bundle = crate::sdk::generate(&graph)?;

    let mut outputs: Vec<(String, Vec<u8>, String)> = Vec::new();
    outputs.push((
        config.output.openapi.clone(),
        openapi.into_bytes(),
        SOURCE_OPENAPI.to_string(),
    ));

    let sdk_dir = config.output.sdk_dir.trim_end_matches('/');
    for (name, contents) in crate::sdk::split_bundle(&bundle) {
        // Frame names are program-controlled, but reject anything that is not a plain file name so a
        // malformed bundle can never traverse out of sdk_dir (mirrors sdk::write_to_dir, T-03-03).
        if name.is_empty() || name.contains('/') || name.contains('\\') || name.contains("..") {
            return Err(crate::CoreError::SdkGen {
                message: format!("refusing to emit SDK file with unsafe name {name:?}"),
            });
        }
        let path = if sdk_dir.is_empty() {
            name
        } else {
            format!("{sdk_dir}/{name}")
        };
        outputs.push((path, contents.into_bytes(), SOURCE_SDK.to_string()));
    }
    Ok(outputs)
}

/// Compute the [`WritePlan`] for `config` WITHOUT touching disk — the dry-run seam `gnr8 check` uses.
///
/// Runs the same graph → outputs pipeline as [`regenerate`], loads the manifest from `.gnr8/`, and
/// classifies each output against the real on-disk bytes via [`plan_writes`], but performs NO writes
/// and does NOT save the manifest. The caller inspects [`WritePlan::has_drift`] to decide an exit code.
///
/// # Errors
///
/// Propagates any pipeline error (Go toolchain missing, lowering, sdkgen, manifest read I/O) as its
/// typed `CoreError`. Never panics.
pub fn plan_only(project_root: &Path, config: &Config) -> Result<WritePlan, crate::CoreError> {
    let outputs = build_outputs(config)?;
    let manifest = manifest::load(&project_root.join(".gnr8"))?;
    let root = project_root.to_path_buf();
    let on_disk = move |path: &str| -> Option<Vec<u8>> { std::fs::read(root.join(path)).ok() };
    Ok(plan_writes_with_sources(&outputs, &manifest, &on_disk))
}

/// Regenerate all outputs for `config`, writing only changed files, and return the outcome counts.
///
/// The orchestrator the binary calls (RESEARCH §architecture). Steps: build the outputs (graph →
/// naming → OpenAPI + SDK), load the manifest from `.gnr8/`, `plan_writes` against the real on-disk
/// bytes, `apply_writes` (honoring `force`), then `manifest.save`. Returns the
/// [`GenerateOutcome`] (written/unchanged/skipped).
///
/// `force=false` ⇒ user-edited / pre-existing outputs are protected (warn + skip at the CLI);
/// `force=true` ⇒ they are overwritten. A no-op run (unchanged source) writes zero files (WATCH-01).
///
/// # Errors
///
/// Propagates any pipeline error (Go toolchain missing, lowering, sdkgen) and any manifest/write I/O
/// error as its typed `CoreError`. Never panics.
pub fn regenerate(
    project_root: &Path,
    config: &Config,
    force: bool,
) -> Result<GenerateOutcome, crate::CoreError> {
    let outputs = build_outputs(config)?;
    let gnr8_dir = project_root.join(".gnr8");
    let mut manifest = manifest::load(&gnr8_dir)?;

    let root = project_root.to_path_buf();
    let on_disk = move |path: &str| -> Option<Vec<u8>> { std::fs::read(root.join(path)).ok() };
    let plan = plan_writes_with_sources(&outputs, &manifest, &on_disk);

    let outcome = apply_writes(project_root, &plan, &mut manifest, force)?;
    manifest.save(&gnr8_dir)?;
    Ok(outcome)
}

#[cfg(test)]
mod tests {
    // Tests legitimately use unwrap/expect/panic (rust-best-practices skill ch.4 + ch.5); scope the
    // allow so the workspace-wide RUST-04 deny stays intact for production code.
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::{apply_writes, safe_output_path, WriteAction};
    use crate::manifest::Manifest;

    #[test]
    fn safe_output_path_rejects_traversal_and_absolute() {
        let root = std::path::Path::new("/tmp/proj");
        assert!(safe_output_path(root, "sdk/client.go").is_ok());
        assert!(safe_output_path(root, "../escape.go").is_err());
        assert!(safe_output_path(root, "sdk/../../etc/passwd").is_err());
        assert!(safe_output_path(root, "/etc/passwd").is_err());
        assert!(safe_output_path(root, "").is_err());
    }

    #[test]
    fn apply_writes_rejects_a_traversal_output_path() {
        // A plan whose path escapes the root must error, not write.
        let plan = super::WritePlan {
            files: vec![super::PlannedFile {
                path: "../escape.go".to_string(),
                action: WriteAction::Write,
                new_bytes: b"x".to_vec(),
                new_hash: "h".to_string(),
                source: "sdk".to_string(),
            }],
        };
        let mut manifest = Manifest::default();
        let result = apply_writes(
            std::path::Path::new("/tmp/proj-does-not-exist"),
            &plan,
            &mut manifest,
            false,
        );
        assert!(
            matches!(result, Err(crate::CoreError::Io { .. })),
            "a traversal path must be rejected with CoreError::Io, got {result:?}"
        );
    }
}
