//! SDK documentation output policy and built-in markdown renderers.
//!
//! Documentation output is part of gnr8's owned SDK surface.

use std::fmt::Write as _;

use crate::graph::{ApiGraph, MediaExample, OperationDocsPolicy, Type};
use crate::sdk::model::SdkModel;
use crate::sdk::Artifacts;

/// SDK documentation output mode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SdkDocs {
    reference: bool,
}

impl SdkDocs {
    /// Do not emit generated SDK documentation.
    #[must_use]
    pub fn none() -> Self {
        Self { reference: false }
    }

    /// Emit the historical gnr8 `README.md` and `reference.md` files.
    #[must_use]
    pub fn reference() -> Self {
        Self { reference: true }
    }

    /// Whether no documentation should be emitted.
    #[must_use]
    pub const fn is_none(&self) -> bool {
        !self.reference
    }
}

impl Default for SdkDocs {
    fn default() -> Self {
        Self::reference()
    }
}

impl From<bool> for SdkDocs {
    fn from(enabled: bool) -> Self {
        if enabled {
            Self::reference()
        } else {
            Self::none()
        }
    }
}

/// Write SDK documentation artifacts under `dir`.
///
pub(crate) fn write_sdk_docs(
    out: &mut Artifacts,
    dir: &str,
    language: &str,
    package: &str,
    ir: &ApiGraph,
    _model: &SdkModel,
    docs: &SdkDocs,
) {
    if docs.is_none() {
        return;
    }
    let dir = dir.trim_end_matches('/');
    if docs.reference {
        out.write(
            format!("{dir}/README.md"),
            sdk_readme(language, package, ir),
        );
        out.write(
            format!("{dir}/reference.md"),
            sdk_reference(language, package, ir),
        );
    }
}

fn sdk_readme(language: &str, package: &str, ir: &ApiGraph) -> String {
    let mut text = format!(
        "# {title} {language} SDK\n\n\
         This directory is generated by `gnr8`. Do not edit generated files directly; edit \
         `.gnr8/src/main.rs` or the source service, then run `gnr8 generate`.\n\n\
         ## Package\n\n\
         - Language: {language}\n\
         - Package/module: `{package}`\n\
         - Base path: `{base_path}`\n\
         - Operations: {operation_count}\n\
         - Schemas: {schema_count}\n\n",
        title = ir.title,
        base_path = ir.base_path,
        operation_count = ir.operations.len(),
        schema_count = ir.schemas.len()
    );
    text.push_str("## Agent workflow\n\n");
    text.push_str("1. Read `reference.md` in this directory for operation and schema names.\n");
    text.push_str(
        "2. Construct the generated `Client` with the service base URL.\n\
         3. Pass typed request models and path/query parameters according to the generated method signatures.\n\
         4. Handle generated `APIError`/`ApiError` values for non-2xx responses.\n\n",
    );
    match language {
        "Go" => text.push_str(
            "## Go quick start\n\n\
             ```go\n\
             client := sdk.NewClient(\"https://api.example.com\")\n\
             // Call methods on client with context.Context first.\n\
             ```\n",
        ),
        "Python" => text.push_str(
            "## Python quick start\n\n\
             ```python\n\
             from sdk import Client\n\
             client = Client(\"https://api.example.com\")\n\
             # Call generated methods with typed models from this package.\n\
             ```\n",
        ),
        "TypeScript" => text.push_str(
            "## TypeScript quick start\n\n\
             ```typescript\n\
             import { Client } from './client';\n\
             const client = new Client('https://api.example.com');\n\
             // Call generated async methods with typed request objects.\n\
             ```\n",
        ),
        _ => {}
    }
    text
}

fn sdk_reference(language: &str, package: &str, ir: &ApiGraph) -> String {
    let mut text = format!(
        "# SDK Reference\n\n\
         Generated by `gnr8` for `{package}` ({language}).\n\n\
         ## Operations\n\n\
         | Method | Path | Operation | Request | Responses |\n\
         |--|--|--|--|--|\n"
    );
    for op in &ir.operations {
        let request = op
            .request_body
            .as_ref()
            .map_or("-", |request| request.ref_id.as_str());
        let responses = op
            .responses
            .iter()
            .map(|response| response.status.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            text,
            "| {} | `{}` | `{}` | `{}` | {} |",
            op.method, op.path, op.id, request, responses
        );
    }
    append_reference_operation_docs(&mut text, ir);
    text.push_str("\n## Schemas\n\n| Schema | Kind |\n|--|--|\n");
    for schema in &ir.schemas {
        let _ = writeln!(
            text,
            "| `{}` | {} |",
            schema.name,
            schema_kind(&schema.body)
        );
    }
    if !ir.diagnostics.is_empty() {
        text.push_str("\n## Diagnostics\n\n");
        for diagnostic in &ir.diagnostics {
            let _ = writeln!(
                text,
                "- {}: {} ({}:{})",
                diagnostic.severity, diagnostic.message, diagnostic.file, diagnostic.line
            );
        }
    }
    text
}

fn append_reference_operation_docs(text: &mut String, ir: &ApiGraph) {
    if ir.operation_docs.is_empty() {
        return;
    }
    text.push_str("\n## Operation Documentation\n\n");
    for policy in &ir.operation_docs {
        let Some(op) = ir
            .operations
            .iter()
            .find(|candidate| candidate.id == policy.operation_id)
        else {
            continue;
        };
        let _ = writeln!(text, "### `{}`\n", op.id);
        append_policy_body(text, None, Some(policy));
    }
}

fn append_policy_body(
    text: &mut String,
    docs: Option<&crate::sdk::model::SdkOperationDocs>,
    policy: Option<&OperationDocsPolicy>,
) {
    let summary = docs
        .and_then(|docs| docs.summary.as_deref())
        .or_else(|| policy.and_then(|policy| policy.summary.as_deref()));
    if let Some(summary) = summary {
        let _ = writeln!(text, "- Summary: {summary}");
    }
    let deprecated = docs.map_or_else(
        || policy.is_some_and(|policy| policy.deprecated),
        |docs| docs.deprecated,
    );
    if deprecated {
        text.push_str("- Deprecated: yes\n");
    }
    let tags = docs
        .map(|docs| docs.tags.as_slice())
        .filter(|tags| !tags.is_empty())
        .or_else(|| {
            policy
                .map(|policy| policy.tags.as_slice())
                .filter(|tags| !tags.is_empty())
        });
    if let Some(tags) = tags {
        let joined = tags
            .iter()
            .map(|tag| format!("`{tag}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(text, "- Tags: {joined}");
    }
    let description = docs
        .and_then(|docs| docs.description.as_deref())
        .or_else(|| policy.and_then(|policy| policy.description.as_deref()));
    if let Some(description) = description {
        let _ = writeln!(text, "\n{description}\n");
    } else if docs.is_some() || policy.is_some() {
        text.push('\n');
    }
    if let Some(policy) = policy {
        append_examples(text, "Request examples", &policy.request_examples);
        for response in &policy.responses {
            if response.description.is_none() && response.examples.is_empty() {
                continue;
            }
            let _ = writeln!(text, "- Response `{}`:", response.status);
            if let Some(description) = &response.description {
                let _ = writeln!(text, "  - Description: {description}");
            }
            append_examples_with_indent(text, "Examples", &response.examples, "  ");
        }
        if !policy.request_examples.is_empty()
            || policy
                .responses
                .iter()
                .any(|response| response.description.is_some() || !response.examples.is_empty())
        {
            text.push('\n');
        }
    }
}

fn append_examples(text: &mut String, label: &str, examples: &[MediaExample]) {
    append_examples_with_indent(text, label, examples, "");
}

fn append_examples_with_indent(
    text: &mut String,
    label: &str,
    examples: &[MediaExample],
    indent: &str,
) {
    if examples.is_empty() {
        return;
    }
    let _ = writeln!(text, "{indent}- {label}:");
    for example in examples {
        let value = serde_json::to_string(&example.value).unwrap_or_else(|_| "null".to_string());
        let _ = writeln!(
            text,
            "{indent}  - `{}` (`{}`): `{}`",
            example.name, example.content_type, value
        );
    }
}

fn schema_kind(schema: &Type) -> &'static str {
    match schema {
        Type::Object(_) => "object",
        Type::Enum(_) => "enum",
        Type::Primitive(_) => "primitive",
        Type::WellKnown(_) => "well-known",
        Type::Array(_) => "array",
        Type::Map { .. } => "map",
        Type::Named(_) => "reference",
        Type::Union(_) => "union",
        Type::Any {} => "any",
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::SdkDocs;

    #[test]
    fn bool_conversion_preserves_legacy_docs_switch() {
        assert!(!SdkDocs::from(true).is_none());
        assert!(SdkDocs::from(false).is_none());
    }
}
